import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { getInterviewHistory, getInterviewProgress, getInterviewResult, startInterviewAnalysis, uploadInterviewDocument } from '../../api/async-scenarios'
import { AsyncState } from '../../components/AsyncState'; import { ResultDocument } from '../../components/ResultDocument'; import { useSessionStore } from '../../app/session-store'; import { PermissionNotice } from '../../components/PermissionNotice'; import { useTaskPolling } from '../async-workbench/useTaskPolling'; import styles from '../async-workbench/AsyncWorkbench.module.css'
import { hasMinimumRole } from '../../app/roles'

export function InterviewDigestPage() {
  const user = useSessionStore(s => s.user); const [content, setContent] = useState(''); const [taskId, setTaskId] = useState<string | null>(null); const [error, setError] = useState(''); const [starting, setStarting] = useState(false); const task = useTaskPolling(taskId, getInterviewProgress, getInterviewResult)
  const allowed = hasMinimumRole(user?.role, 'hrbp')
  const history = useQuery({ queryKey: ['interview-history'], queryFn: getInterviewHistory, enabled: allowed })
  const latest = history.data?.digests?.find(d => d.result) ?? null
  useEffect(() => { if (task.phase === 'completed') history.refetch() }, [task.phase]) // eslint-disable-line react-hooks/exhaustive-deps
  if (!allowed) return <main className="page-stack"><header className="page-heading"><div><h1>面谈纪要</h1></div></header><PermissionNotice feature="面谈纪要" /></main>
  async function start() { if (content.trim().length < 50) return setError('至少需要50字'); setStarting(true); setError(''); try { const result = await startInterviewAnalysis(content.trim()); setTaskId(result.task_id) } catch (e) { setError(e instanceof Error ? e.message : '分析未启动') } finally { setStarting(false) } }
  async function upload(file?: File) { if (!file) return; try { const result = await uploadInterviewDocument(file); setContent(result.content) } catch (e) { setError(e instanceof Error ? e.message : '文件解析失败') } }
  return <main className="page-stack"><header className="page-heading"><div><span className="eyebrow">面谈整理</span><h1>面谈纪要</h1><p>先核对原文，再提交异步分析。结果用于辅助整理，不替代 HR 判断。</p></div></header><div className={styles.grid}><section className={styles.editor}><div className={styles.toolbar}><strong>面谈原文</strong><label className="secondary-button">导入文件<input hidden type="file" accept=".txt,.pdf,.docx" onChange={e => upload(e.target.files?.[0])} /></label></div><label><span>面谈内容</span><textarea value={content} onChange={e => setContent(e.target.value)} rows={18} placeholder="粘贴访谈记录，至少 50 字…" /></label><div className={styles.actions}><small>{content.trim().length} 字</small><button className="primary-button" onClick={start} disabled={starting || task.phase === 'queued' || task.phase === 'processing'}>{starting ? '正在提交…' : '开始分析'}</button></div>{error && <p className={styles.error} role="alert">{error}</p>}</section><section className={styles.result}><h2>结构化纪要</h2>{task.phase === 'idle' && !latest && <AsyncState kind="empty" title="还没有分析结果" detail="完整输入面谈记录后开始分析。" />}{task.phase === 'idle' && latest?.result != null && <><p className={styles.historyNote}>最近完成于 {formatTime(latest.completed_at ?? latest.created_at)}</p><ResultDocument result={latest.result as Record<string, unknown>} /></>}{task.phase === 'queued' && <AsyncState kind="processing" title="排队中" detail="任务已提交，正在等待分析。" />}{task.phase === 'processing' && <AsyncState kind="processing" title="正在分析" detail="任务在后端运行，完成后会自动显示结果。" />}{task.phase === 'error' && <AsyncState kind="error" title="分析失败" detail={task.error ?? undefined} action={<button onClick={task.retry}>重试读取</button>} />}{task.result && <ResultDocument result={task.result} />}</section></div></main>
}

function formatTime(value: unknown) { const date = value ? new Date(String(value)) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—' }
